### PR TITLE
Add GitHub Actions Workflow for the Project

### PR DESCRIPTION
**Pull request by hayschan**
This pull request introduces a GitHub Actions workflow to automate the compilation of ESP-IDF sketches for versions 5.0 and 5.1, targeting both ESP32 and ESP32-S3. The workflow will be triggered on pull requests and pushes to relevant files, ensuring that code changes are validated through continuous integration.

### Details

- **Workflow Name:** Compile ESP-IDF Sketches for v5.1
- **Trigger Events:** 
  - Pull requests and pushes to the following paths:
    - `.github/workflows/espidf-compile-*.yml`
    - `main/**`
    - `components/**`
    - `CMakeLists.txt`
    - `Kconfig`
    - `partitions.csv`
    - `sdkconfig.defaults`
  - Manual dispatch via `workflow_dispatch` and `repository_dispatch`

I have tested the GitHub Actions workflow on my branch before opening this PR. The actions work as expected and successfully compile the ESP-IDF sketches for the specified versions and targets.

Please review the workflow configuration and provide feedback or suggestions for improvement.

### CODE REVIEW

**Comment by nopnop2002** [comment]
Why is this the only target?

This repository supports all ESP32 and all versions since 4.4.

```
        idf_ver:
          - release-v5.0
          - release-v5.1
        idf_target:
          - esp32
          - esp32s3
 ```

**Comment by hayschan** [comment]
Thanks for the reminder. Let me add more targets to the Actions.

**Comment by hayschan** [comment]
In the latest commit, the matrix will create 20 ( $= 5 \times 4$ ) distinct tests, each one compiling the application for a different combination of ESP-IDF version and target. I have chosen four most popular chips.

If we add even more hardware targets to the test, it would make our testing matrix extremely large. 

```yaml
 idf_ver:
          - release-v4.4
          - release-v5.0
          - release-v5.1
          - release-v5.2
          - release-v5.3
        idf_target:
          - esp32
          - esp32s2
          - esp32c3
          - esp32s3
```

**Comment by hayschan** [comment]
> This repository supports all ESP32 and all versions since 4.4.

In my testing, all the following version builds in success except `release-v4.4`.

1. release-v4.4
2. release-v5.0
3. release-v5.1
4. release-v5.2
5. release-v5.3

Here is the error:

```python
/app/hayschan/esp-idf-serial/components/serial/serial.c: In function 'serial_begin':
/app/hayschan/esp-idf-serial/components/serial/serial.c:89:17: error: 'UART_SCLK_DEFAULT' undeclared (first use in this function); did you mean 'UART_SCLK_REF_TICK'?
   .source_clk = UART_SCLK_DEFAULT,
                 ^~~~~~~~~~~~~~~~~
                 UART_SCLK_REF_TICK
/app/hayschan/esp-idf-serial/components/serial/serial.c:89:17: note: each undeclared identifier is reported only once for each function it appears in
ninja: build stopped: subcommand failed.
ninja failed with exit code 1
Error: Process completed with exit code 2.
```

**Comment by nopnop2002** [comment]
>I have chosen four most popular chips.

I think that is fine.

>all the following version builds in success except release-v4.4

This PR was immediately helpful.

thank you.
